version: '2'

services:
    #defino los servivios de los servidor node.js y el de python
    # puerto 4000: servidor node.js
    # puerto 4001: servidor python
    
    servernodejs:
                build: ./js
                ports: 
                    - "4000:8080"    #mapeo el puerto 8080 del contenedor al 4000 del host
    serverpython:
                build: ./py
                ports: 
                    - "4001:8000"    #mapeo el puerto 8000 del contenedor al 4001 del host
        


    #IMPORTANTE: Comente las lineas siguientes para solo probar los servidores
    
                
    # nginx:
    #     image: nginx:1.17.8
    #     ports:
    #         - "5555:80"
    #     volumes:
    #         - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    #         - ./store/static/files:/static:ro
    #     links:
    #         - gunicorn
    #         - node

#     graphite:
#         image: graphiteapp/graphite-statsd:1.1.5-12
#         volumes:
#             - ./statsd.config.js:/opt/statsd/config.js
#             - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
#         ports:
#             - "8090:80"
#             - "8125:8125/udp"
#             - "8126:8126"

#     grafana:
#         image: grafana/grafana:6.3.3
#         ports:
#             - "80:3000"
#         volumes:
#             - "grafana_config:/var/lib/grafana"

#     cadvisor:
#         image: google/cadvisor:v0.33.0
#         links:
#             - graphite
#         command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
#         ports:
#             - "8080:8080"
#         volumes:
#             - "/:/rootfs:ro"
#             - "/var/run:/var/run:rw"
#             - "/sys:/sys:ro"
#             - "/var/lib/docker/:/var/lib/docker:ro"

# volumes:
#     grafana_config:
#         driver: local
