version: '3'

services:
    node:
        build: ./js
        ports: 
            - "4000:8080"    #mapeo el puerto 8080 del contenedor al 4000 del host
        container_name: node

    gunicorn:
        build: ./py
        ports: 
            - "4001:8000"    #mapeo el puerto 8000 del contenedor al 4001 del host

    gunicorn_1:
        build: ./py

    gunicorn_2:
        build: ./py
    
    gunicorn_3:
        build: ./py
        
    nginx:
        restart: always
        image: nginx:1.17.8
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node
            - gunicorn         

    graphite:
        image: graphiteapp/graphite-statsd:1.1.5-12
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:6.3.3
        ports:
            - "81:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: google/cadvisor:v0.33.0
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local
